version: '3.9'

services:
    java-skeleton-api:
        container_name: java-skeleton-api
        image: gradle:latest # this is due to some Mac M1 issues with Docker :_
        volumes:
            -   "./:/home/gradle/project"
            -   "rv-gradle-cache:/home/gradle/.gradle"
        working_dir: "/home/gradle/project"
        ports:
            -   "8080:8080"
        networks:
            internal-net:

volumes:
    rv-gradle-cache:

networks:
    internal-net:
        name: rv-skeleton-net
